### ISSUE TITLE
Pengkhususan OS

### ISSUE THREAD

**Issue by hasyimibhar** [kidino/buku-git#7]
`content/git_init_--_memulakan_projek_baru.md` menggunakan arahan yang khusus untuk pengguna Windows (penggunaan `Git Bash` dan screenshot yang khusus untuk Windows.) Adakah buku ini akan lebih fokus kepada pengguna Windows?

Jika tidak, saya syorkan untuk menggunakan arahan Unix (yang mudah-mudah sahaja, seperti `cd`, `mkdir`) sahaja supaya lebih selari untuk semua pembaca. Ini tidak menjadi masalah untuk pengguna Windows, kerana Git Bash membolehkan penggunaan arahan Unix.

Arahan-arahan yang khusus kepada OS tertentu hanya perlu diadakan untuk bahagian pemasangan Git.

**Comment by adyromantika** [comment]
Saya setuju. Ini membolehkan pembaca lebih fokus kepada arahan git tidak kira apa platform yang digunakan mereka.

**Comment by kidino** [comment]
Saya dalam 80% bersetuju. Kalau begitu, bermakna semua screenshot terminal dan command prompt perlu dibuang dan digantikan dengan arahan-arahan dengan `<pre>` sahaja.

Screenshot sekadar menunjukkan -- ini adalah terminal / command prompt.

Nanti saya putuskan.

**Comment by kidino** [comment]
baiklah ... cadangan diterima.
